---
- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300

- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - bash-completion
    - curl
    - git
    - htop
    - mc
    - ncdu
    - python3
    - python-dev
    - python-pip
    - python-setuptools
    - screen
    - sudo
    - tmux
    - tree
    - wget

- name: Make sure pip upgraded (fixes docker-py errors)
  command: easy_install -U pip

- name: install docker-py
  pip:
    name: docker-py
    state: present
    extra_args: -U
