version: "2"
services:
  db:
    image: mattermost/mattermost-prod-db
    restart: always
    volumes:
      - /opt/mattermost/db/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    # uncomment the following to enable backup
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    image: mattermost/mattermost-prod-app
    restart: always
    volumes:
      - /opt/mattermost/config:/mattermost/config:rw
      - /opt/mattermost/data:/mattermost/data:rw
      - /etc/localtime:/etc/localtime:ro

  web:
    image: mattermost/mattermost-prod-web
    ports:
      - "8080:80"
      - "8443:443"
    restart: always
    volumes:
      # This directory must have cert files
      - /opt/mattermost/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MATTERMOST_ENABLE_SSL=false
      - PLATFORM_PORT_80_TCP_PORT=80
