---
- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - python3
    - python-dev
    - python-pip
    - python-setuptools

- name: Make sure pip upgraded (fixes docker-py errors)
  command: easy_install -U pip

- name: install docker-py
  pip:
    name: docker-py
    state: present
    extra_args: -U

- name: install docker-compose
  pip:
    name: docker-compose
    state: present
    extra_args: -U
